image: node:24

pipelines:
  branches:
    main:
      - step:
          name: Build Eleventy Site
          caches:
            - node
          script:
            - npm ci
            - npm run build
          artifacts:
            - _site/**